#
# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#
version: '3'

networks:
  basic:
       
services:
  PostgreSQL:
    container_name: postgresql
    hostname: localhost
    # restart: always
    image: postgres:9.6
    environment:
      - DEBUG=false
      - DB_USER=matic
      - DB_PASS=password
      - DB_NAME=
      - DB_TEMPLATE=
      - DB_EXTENSION=
      - REPLICATION_MODE=
      - REPLICATION_USER=
      - REPLICATION_PASS=
      - REPLICATION_SSLMODE=
    volumes:
      - ./dbsql.sql:/docker-entrypoint-initdb.d/1-schema.sql
    networks:
      - basic
    ports:
      - "5050:5432"
      
  matic-eth:
    container_name: matic_eth
    build: .
    networks:
      - basic
    ports:
      - "8010:8010"
